/*
 * Swagger Blog
 *
 * A Simple Blog
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Article struct {

	Id int `json:"id"`

	Name string `json:"name"`

	Tags []Tag `json:"tags,omitempty"`

	Date string `json:"date,omitempty"`

	Content string `json:"content"`
}


type ArticleResponse struct {

	Id int `json:"id,omitempty"`

	Name string `json:"name,omitempty"`
}


type ArticlesResponse struct {
	Articles []ArticleResponse`json:"articles,omitempty"`
}

/*type ArticleCreate struct {

	Content string `json:"content,omitempty"`

	Tags []string `json:"tags,omitempty"`

	Name string `json:"name,omitempty"`
}*/